/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Use atomics for fgetc/ungetc for re-entrancy */
#define ATOMIC_UNGETC

/* Always optimize strcmp for performance */
#define FAST_STRCMP

#define HAVE_ALIAS_ATTRIBUTE

#define HAVE_FORMAT_ATTRIBUTE

/* IEEE fp funcs available */
#define HAVE_IEEEFP_FUNCS

/* compiler supports INIT_ARRAY sections */
#define HAVE_INITFINI_ARRAY

/* Support _init() and _fini() functions */
#define HAVE_INIT_FINI

/* Semihost APIs supported */
#define HAVE_SEMIHOST

/* use regular syscalls */
#undef MISSING_SYSCALL_NAMES

/* use global errno variable */
#undef NEWLIB_GLOBAL_ERRNO

/* use thread local storage */
#define NEWLIB_TLS

/* use thread local storage */
#define PICOLIBC_TLS

/* Use POSIX I/O for stdin, stdout and stderr */
#undef POSIX_CONSOLE

/* Use open/close/read/write in tinystdio */
#define POSIX_IO

/* Optimize for space over speed */
#define PREFER_SIZE_OVER_SPEED

/* Reentrant syscalls provided for us */
#undef REENTRANT_SYSCALLS_PROVIDED

/* Use tiny stdio from gcc avr */
#define TINY_STDIO

#undef _ATEXIT_DYNAMIC_ALLOC

#undef _FSEEK_OPTIMIZATION

#undef _FVWRITE_IN_STREAMIO

/* GCC flag to prevent detecting memcpy/memset patterns */
#define _HAVE_CC_INHIBIT_LOOP_TO_LIBCALL

/* Compiler has long double type */
#define _HAVE_LONG_DOUBLE

#undef _ICONV_ENABLE_EXTERNAL_CCS

#define _ICONV_FROM_ENCODING_

#define _ICONV_FROM_ENCODING_BIG5

#define _ICONV_FROM_ENCODING_CP775

#define _ICONV_FROM_ENCODING_CP850

#define _ICONV_FROM_ENCODING_CP852

#define _ICONV_FROM_ENCODING_CP855

#define _ICONV_FROM_ENCODING_CP866

#define _ICONV_FROM_ENCODING_EUC_JP

#define _ICONV_FROM_ENCODING_EUC_KR

#define _ICONV_FROM_ENCODING_EUC_TW

#define _ICONV_FROM_ENCODING_ISO_8859_1

#define _ICONV_FROM_ENCODING_ISO_8859_10

#define _ICONV_FROM_ENCODING_ISO_8859_11

#define _ICONV_FROM_ENCODING_ISO_8859_13

#define _ICONV_FROM_ENCODING_ISO_8859_14

#define _ICONV_FROM_ENCODING_ISO_8859_15

#define _ICONV_FROM_ENCODING_ISO_8859_2

#define _ICONV_FROM_ENCODING_ISO_8859_3

#define _ICONV_FROM_ENCODING_ISO_8859_4

#define _ICONV_FROM_ENCODING_ISO_8859_5

#define _ICONV_FROM_ENCODING_ISO_8859_6

#define _ICONV_FROM_ENCODING_ISO_8859_7

#define _ICONV_FROM_ENCODING_ISO_8859_8

#define _ICONV_FROM_ENCODING_ISO_8859_9

#define _ICONV_FROM_ENCODING_ISO_IR_111

#define _ICONV_FROM_ENCODING_KOI8_R

#define _ICONV_FROM_ENCODING_KOI8_RU

#define _ICONV_FROM_ENCODING_KOI8_U

#define _ICONV_FROM_ENCODING_KOI8_UNI

#define _ICONV_FROM_ENCODING_UCS_2

#define _ICONV_FROM_ENCODING_UCS_2BE

#define _ICONV_FROM_ENCODING_UCS_2LE

#define _ICONV_FROM_ENCODING_UCS_2_INTERNAL

#define _ICONV_FROM_ENCODING_UCS_4

#define _ICONV_FROM_ENCODING_UCS_4BE

#define _ICONV_FROM_ENCODING_UCS_4LE

#define _ICONV_FROM_ENCODING_UCS_4_INTERNAL

#define _ICONV_FROM_ENCODING_US_ASCII

#define _ICONV_FROM_ENCODING_UTF_16

#define _ICONV_FROM_ENCODING_UTF_16BE

#define _ICONV_FROM_ENCODING_UTF_16LE

#define _ICONV_FROM_ENCODING_UTF_8

#define _ICONV_FROM_ENCODING_WIN_1250

#define _ICONV_FROM_ENCODING_WIN_1251

#define _ICONV_FROM_ENCODING_WIN_1252

#define _ICONV_FROM_ENCODING_WIN_1253

#define _ICONV_FROM_ENCODING_WIN_1254

#define _ICONV_FROM_ENCODING_WIN_1255

#define _ICONV_FROM_ENCODING_WIN_1256

#define _ICONV_FROM_ENCODING_WIN_1257

#define _ICONV_FROM_ENCODING_WIN_1258

#define _ICONV_TO_ENCODING_

#define _ICONV_TO_ENCODING_BIG5

#define _ICONV_TO_ENCODING_CP775

#define _ICONV_TO_ENCODING_CP850

#define _ICONV_TO_ENCODING_CP852

#define _ICONV_TO_ENCODING_CP855

#define _ICONV_TO_ENCODING_CP866

#define _ICONV_TO_ENCODING_EUC_JP

#define _ICONV_TO_ENCODING_EUC_KR

#define _ICONV_TO_ENCODING_EUC_TW

#define _ICONV_TO_ENCODING_ISO_8859_1

#define _ICONV_TO_ENCODING_ISO_8859_10

#define _ICONV_TO_ENCODING_ISO_8859_11

#define _ICONV_TO_ENCODING_ISO_8859_13

#define _ICONV_TO_ENCODING_ISO_8859_14

#define _ICONV_TO_ENCODING_ISO_8859_15

#define _ICONV_TO_ENCODING_ISO_8859_2

#define _ICONV_TO_ENCODING_ISO_8859_3

#define _ICONV_TO_ENCODING_ISO_8859_4

#define _ICONV_TO_ENCODING_ISO_8859_5

#define _ICONV_TO_ENCODING_ISO_8859_6

#define _ICONV_TO_ENCODING_ISO_8859_7

#define _ICONV_TO_ENCODING_ISO_8859_8

#define _ICONV_TO_ENCODING_ISO_8859_9

#define _ICONV_TO_ENCODING_ISO_IR_111

#define _ICONV_TO_ENCODING_KOI8_R

#define _ICONV_TO_ENCODING_KOI8_RU

#define _ICONV_TO_ENCODING_KOI8_U

#define _ICONV_TO_ENCODING_KOI8_UNI

#define _ICONV_TO_ENCODING_UCS_2

#define _ICONV_TO_ENCODING_UCS_2BE

#define _ICONV_TO_ENCODING_UCS_2LE

#define _ICONV_TO_ENCODING_UCS_2_INTERNAL

#define _ICONV_TO_ENCODING_UCS_4

#define _ICONV_TO_ENCODING_UCS_4BE

#define _ICONV_TO_ENCODING_UCS_4LE

#define _ICONV_TO_ENCODING_UCS_4_INTERNAL

#define _ICONV_TO_ENCODING_US_ASCII

#define _ICONV_TO_ENCODING_UTF_16

#define _ICONV_TO_ENCODING_UTF_16BE

#define _ICONV_TO_ENCODING_UTF_16LE

#define _ICONV_TO_ENCODING_UTF_8

#define _ICONV_TO_ENCODING_WIN_1250

#define _ICONV_TO_ENCODING_WIN_1251

#define _ICONV_TO_ENCODING_WIN_1252

#define _ICONV_TO_ENCODING_WIN_1253

#define _ICONV_TO_ENCODING_WIN_1254

#define _ICONV_TO_ENCODING_WIN_1255

#define _ICONV_TO_ENCODING_WIN_1256

#define _ICONV_TO_ENCODING_WIN_1257

#define _ICONV_TO_ENCODING_WIN_1258

/* math library does not set errno (offering only ieee semantics) */
#define _IEEE_LIBM

#define _IO_FLOAT_EXACT

/* long double is the same as double */
#undef _LDBL_EQ_DBL

#define _LITE_EXIT

#undef _MB_CAPABLE

#define _MB_LEN_MAX 1

#undef _NANO_FORMATTED_IO

#define _NANO_MALLOC

/* The newlib minor version number. */
#define _NEWLIB_MINOR__ 3

/* The newlib version in string format. */
#define _NEWLIB_VERSION "3.3.0"

/* The newlib major version number. */
#define _NEWLIB__ 3

/* The Picolibc minor version number. */
#define _PICOLIBC_MINOR__ 4

/* The Picolibc version in string format. */
#define _PICOLIBC_VERSION "1.4.6"

/* The Picolibc major version number. */
#define _PICOLIBC__ 1

#undef _REENT_GLOBAL_ATEXIT

#undef _RETARGETABLE_LOCKING

#undef _UNBUF_STREAM_OPT

#define _WANT_IO_C99_FORMATS

#undef _WANT_IO_LONG_LONG

#undef _WANT_REENT_SMALL

#undef _WANT_REGISTER_FINI

#undef _WANT_USE_LONG_TIME_T

#undef _WIDE_ORIENT

/* extended locale support */
#undef __HAVE_LOCALE_INFO_EXTENDED__

/* locale support */
#undef __HAVE_LOCALE_INFO__

/* The newlib patch level. */
#define __NEWLIB_PATCHLEVEL__ 0

/* Use old math code (undef auto, 0 no, 1 yes) */
#undef __OBSOLETE_MATH

/* The Picolibc patch level. */
#define __PICOLIBC_PATCHLEVEL__ 6

#define __SINGLE_THREAD__

